//
//  OpenSSHKeyTests.swift
//  sshconfigmanagerTests
//
//  Validates the OpenSSH private-key parser against a real (throwaway) key:
//  the parsed seed must derive, via CryptoKit, the same public key the parser
//  read from the file — proving the parse is correct end to end.
//

import CryptoKit
import Foundation
import SSHConfigCore
import SSHConfigCrypto
import SSHConfigServices
import Testing

@testable import SSHConfigMacUI

struct OpenSSHKeyTests {
    /// A throwaway unencrypted ed25519 key generated by ssh-keygen (test only).
    private let unencryptedEd25519 = """
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
        QyNTUxOQAAACCyAn5NRmG+y/ppGE5TkyYYq5u2dAUOXv2R/4h/iDWsKQAAAJidu9d1nbvX
        dQAAAAtzc2gtZWQyNTUxOQAAACCyAn5NRmG+y/ppGE5TkyYYq5u2dAUOXv2R/4h/iDWsKQ
        AAAEDovZ9fte4yiNTzU5CmKigp+BjeATCils/78K5rgql9qLICfk1GYb7L+mkYTlOTJhir
        m7Z0BQ5e/ZH/iH+INawpAAAAEXR1bm5lbC10ZXN0QGxvY2FsAQIDBA==
        -----END OPENSSH PRIVATE KEY-----
        """

    /// A throwaway unencrypted ECDSA P-256 key (ssh-keygen).
    private let unencryptedEcdsaP256 = """
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
        1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQTP5z3HLtCxuYNI/McX5KoJJMB8Lwsj
        t43r38+XSI6cVzWCAcpof/+dWmahBGoxlzwGoRySw7DA6/bDSmPC2RB0AAAAqNlP4OXZT+
        DlAAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBM/nPccu0LG5g0j8
        xxfkqgkkwHwvCyO3jevfz5dIjpxXNYIBymh//51aZqEEajGXPAahHJLDsMDr9sNKY8LZEH
        QAAAAgdexsPsTzUUcrFM07cy2qMUhoyfK1oFT+CXGlagCk90wAAAANZWMtdGVzdEBsb2Nh
        bAECAw==
        -----END OPENSSH PRIVATE KEY-----
        """

    @Test func parsesUnencryptedEd25519() throws {
        let parsed = try OpenSSHPrivateKey.parse(pem: unencryptedEd25519)
        #expect(parsed.keyType == "ssh-ed25519")
        #expect(parsed.ed25519Seed?.count == 32)
        #expect(parsed.publicKey.count == 32)
    }

    @Test func parsedSeedDerivesTheStoredPublicKey() throws {
        let parsed = try OpenSSHPrivateKey.parse(pem: unencryptedEd25519)
        // The whole point: seed → CryptoKit private key → public key must match
        // the public key bytes the parser independently read from the file.
        let seed = try #require(parsed.ed25519Seed)
        let key = try Curve25519.Signing.PrivateKey(rawRepresentation: seed)
        #expect([UInt8](key.publicKey.rawRepresentation) == parsed.publicKey)
    }

    @Test func parsesEcdsaP256AndScalarDerivesPoint() throws {
        let parsed = try OpenSSHPrivateKey.parse(pem: unencryptedEcdsaP256)
        #expect(parsed.keyType == "ecdsa-sha2-nistp256")
        guard case .ecdsa(let curve, let scalar) = parsed.material else {
            Issue.record("expected ecdsa material")
            return
        }
        #expect(curve == .p256)
        #expect(scalar.count == 32)
        // The scalar must reconstruct the public EC point (x963 = 0x04‖X‖Y) the
        // parser read independently from the file.
        let key = try P256.Signing.PrivateKey(rawRepresentation: Data(scalar))
        #expect([UInt8](key.publicKey.x963Representation) == parsed.publicKey)
    }

    private func sshStr(_ s: String) -> [UInt8] { SSHAgentProtocol.string(Array(s.utf8)) }

    @Test func rejectsUnsupportedKDF() {
        // cipher is supported (aes256-ctr) but the KDF isn't bcrypt → unsupportedKDF.
        var blob = Array("openssh-key-v1\0".utf8)
        blob += sshStr("aes256-ctr") + sshStr("scrypt") + sshStr("") + [0, 0, 0, 1]
        blob += sshStr("pub") + sshStr("priv")
        let pem =
            "-----BEGIN OPENSSH PRIVATE KEY-----\n\(Data(blob).base64EncodedString())\n-----END OPENSSH PRIVATE KEY-----"
        #expect(throws: OpenSSHKeyError.unsupportedKDF("scrypt")) {
            try OpenSSHPrivateKey.parse(pem: pem)
        }
    }

    @Test func rejectsNonOpenSSHText() {
        #expect(throws: OpenSSHKeyError.self) {
            try OpenSSHPrivateKey.parse(pem: "not a key")
        }
    }

    /// A throwaway ed25519 key encrypted (aes256-ctr / bcrypt) with passphrase "hunter2".
    private let encryptedEd25519 = """
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABACZOWjdA
        MCFAIVMfEmvJL+AAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIHmj12rCUiiVT2J/
        5lCNLndG1KC/u6wK525jLcdGnqWBAAAAoOr/xDQA74UZn6wg/1QtnWMFOiqbuNUULPVBP3
        e5qi/kpnkEsypeMgAydJQmk72YlwSFhXHGKlOZUW7/tdCvgXr3VeitwK1KLv+p7TabmhDA
        thLTFaHYI166a3dyBTmLs3c0FOpDVsDXom4NquEd0JoRSt9QwFjJzpLM3k9UB38gotANoY
        XnqbJttOYanWMkL0C2bbtYYl4yw1oFCXgX6oU=
        -----END OPENSSH PRIVATE KEY-----
        """
    /// The public key bytes for the encrypted key above (base64 of the 32-byte ed25519 point).
    private let encryptedPublicKeyB64 = "eaPXasJSKJVPYn/mUI0ud0bUoL+7rArnbmMtx0aepYE="

    @Test func decryptsPassphraseProtectedEd25519() throws {
        // The whole bcrypt_pbkdf + AES-CTR chain: with the right passphrase, the
        // recovered seed must derive the key's real public key.
        let parsed = try OpenSSHPrivateKey.parse(pem: encryptedEd25519, passphrase: "hunter2")
        #expect(parsed.keyType == "ssh-ed25519")
        let seed = try #require(parsed.ed25519Seed)
        let key = try Curve25519.Signing.PrivateKey(rawRepresentation: seed)
        #expect([UInt8](key.publicKey.rawRepresentation) == parsed.publicKey)
        #expect(Data(parsed.publicKey).base64EncodedString() == encryptedPublicKeyB64)
    }

    @Test func wrongPassphraseIsRejected() {
        #expect(throws: OpenSSHKeyError.incorrectPassphrase) {
            try OpenSSHPrivateKey.parse(pem: encryptedEd25519, passphrase: "wrong")
        }
    }

    @Test func encryptedKeyWithoutPassphraseAsksForOne() {
        #expect(throws: OpenSSHKeyError.passphraseRequired) {
            try OpenSSHPrivateKey.parse(pem: encryptedEd25519)
        }
    }

    // MARK: - RSA (NIOSSHRSA custom-key support)

    /// A throwaway unencrypted RSA-2048 key (ssh-keygen, test only).
    private let unencryptedRSA = """
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
        NhAAAAAwEAAQAAAQEA0W6xEDkrdKfs24OeK5z/iSyjBJkk4ICU48qETI3Ukk+Jc93HDMgK
        o3LFRQt3YkkJdGkGqkAK6ZNQqpMsS6cYWlcbiK+TAjrsf+fdEChjVst8SJ6a7zg9Uewib5
        MOvkiuXDNaOr83i71HKwnMqGPkPkig1WxeYnVB4LBjp2QUQkGhCyOKeML7U6GpgBYVVt6H
        qlxWufolGF6mxC8xJfgDileULX9qayH2urDWRfGC4ufHyUr+ezqHU785bDj+4JMdsW7ybF
        rJnHlFLXifJ4ar3PCEuiCwKX8k8VkrYucHz+G2KcVh+DFVYHj1yZwpCRpJEgqXLGsOIHex
        oaxb4yNyHQAAA8ia9gVVmvYFVQAAAAdzc2gtcnNhAAABAQDRbrEQOSt0p+zbg54rnP+JLK
        MEmSTggJTjyoRMjdSST4lz3ccMyAqjcsVFC3diSQl0aQaqQArpk1CqkyxLpxhaVxuIr5MC
        Oux/590QKGNWy3xInprvOD1R7CJvkw6+SK5cM1o6vzeLvUcrCcyoY+Q+SKDVbF5idUHgsG
        OnZBRCQaELI4p4wvtToamAFhVW3oeqXFa5+iUYXqbELzEl+AOKV5Qtf2prIfa6sNZF8YLi
        58fJSv57OodTvzlsOP7gkx2xbvJsWsmceUUteJ8nhqvc8IS6ILApfyTxWSti5wfP4bYpxW
        H4MVVgePXJnCkJGkkSCpcsaw4gd7GhrFvjI3IdAAAAAwEAAQAAAQBqr7GhKw5ZAcYl2Ll1
        TCfcUBHHIOBpQPcXxy139fQoiD3j+UER4MGSm7+kOYAaYExhsbLEfZVRgUrhadFxxHAibS
        dIjPAdfbjGO24gcgKQz13DfJA+dm6+UcUFA2vKQSoZK8u2C3yXQdeENBy+VwyJMeREdEzs
        aQEjHZfWSKQNT4aQJV8qndVVsBZYnBKeuO2qlpoPG7xUYE0MqQi0RlCoN2PjckKJ7paOwL
        EyZ7zrjR6rmEpjjgZCOxMXMU1Jh+22HXdFhodRwUH87IAhFNq6R1i8IVQpGGgEYLw4WzPj
        +k8HOHQiJrzkLPzkqCTjd0axRXVqvTbiTjk0Bl2D2SwhAAAAgQDMApoJGf3VUx5do5asSp
        jvz1BF82SXDwhuA1Zh/YN2kXoPLqUJVoykuC3fUTAjlhOxAd/vEdpDCbdk58sPQvB3qJrB
        wwjpc5F70NcHiojkbRnIi5iObp+p3F551qDJQMNvtUOCdjmSYVrFIJyMAdVioO7rOxB68S
        D1Bet4f9pWwAAAAIEA/N9CY4/Gv2DXpNJeY+sVq+X5qMjqTz7rljIJ3fdshTLm1jHYS3Y4
        JoPYS3AQSjGBxSc7H7v+njGY3NIioLqrPTiRgpus0MkBsJerNtc4fbPWIxXMSWnP+FosSX
        fxIK1pjpNMSs9slFYMPbO/xtxkoG/so1TdSyY223oyhZkZ+lUAAACBANQF4HeWH6dQNtYS
        +Mc7EJsk2yAPjUZRGQ+REF9yzHNdSnJedoc39GY1JjiAjqIkhQLCB9lxHaNto89C3AxOvK
        B3TpeY7xVHvfHriSskA7WEYES8tMWheahVIbp819t4VdrpBjQ9YaapvvtqBpuM65B5eY7l
        vhq0V51W2F2NmHCpAAAADnJzYS10ZXN0QGxvY2FsAQIDBA==
        -----END OPENSSH PRIVATE KEY-----
        """
    /// The base64 body (after "ssh-rsa ") of the unencrypted RSA key's .pub file.
    private let unencryptedRSAPubB64 =
        "AAAAB3NzaC1yc2EAAAADAQABAAABAQDRbrEQOSt0p+zbg54rnP+JLKMEmSTggJTjyoRMjdSST4lz3ccMyAqjcsVFC3diSQl0aQaqQArpk1CqkyxLpxhaVxuIr5MCOux/590QKGNWy3xInprvOD1R7CJvkw6+SK5cM1o6vzeLvUcrCcyoY+Q+SKDVbF5idUHgsGOnZBRCQaELI4p4wvtToamAFhVW3oeqXFa5+iUYXqbELzEl+AOKV5Qtf2prIfa6sNZF8YLi58fJSv57OodTvzlsOP7gkx2xbvJsWsmceUUteJ8nhqvc8IS6ILApfyTxWSti5wfP4bYpxWH4MVVgePXJnCkJGkkSCpcsaw4gd7GhrFvjI3Id"

    /// A throwaway RSA-2048 key encrypted (aes256-ctr / bcrypt) with passphrase "hunter2".
    private let encryptedRSA = """
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCVb/ljY4
        9qgKsRAa1NxiykAAAAGAAAAAEAAAEXAAAAB3NzaC1yc2EAAAADAQABAAABAQDWZwib2Xs2
        4kqvkfd17EwR/oZM5Wyk62trNPC2JSI7YuZOMQVVkB75fTnxby17d4wA+Imtz9LC4jEzwZ
        u5+lfhbW5ifTYYbTlTNwzrKe4/gLygVpFn0uT0SprnSSpJEx3m+4+YnycLsPn4T5xLEja2
        7S7T6eVo+KDqgYGzdShotYUF6UNhJZ7H6tWBPp2Ei+9gHmgII7f8ZpdSxjXI3GfiatMDdp
        395bckT6Y3AgS9KWZbB5gWBnPs/rMuewAJe7b3AdsTtJIhsU+81Ozv9CkZ2F+nfsesCMU6
        2IC6ctfK5Jl7Xf4M3/lLLvJ2IEPX05iTQh2TjQf59y+td5HnPdP3AAAD0EbUTuyDYGdlj7
        YTziKz7ti7JFTXMtC3Pv807hqllFfMElLA/9NB/g/oWzMgiAJQ0f6iyMj9NdkUOWVqBLL9
        ZEgFsSmOObSwcMZbOUcEo3o0+k4a5SaNisLnJp1wAV/N64dgjqwrmRIzIOZZEIWK4HD6Ay
        YL1EpcmkK8qlJgPfSvbjGUd9EaZGaoJsD+gTHCUeMevrWPuIjhSd99+zjYDWxiBDWrw+No
        Mo+MrBeawIzgnPQ0tf4oXtLPCqa0o/aBiv2bjFlMRy6gkGLFPUa7xOHW37wLdRVSL5uQxV
        mvFKRjkGUcLI8LFeW/aAHW5wdj+gY9GET127ecJgh6U3RWORjM81+sW7N1bi/V/v3CqwZE
        xS9P7U8a5PHanGjYASND5wcWa0AvpY4Wai9wUg5NRfdnPKfrbJta3mxttISUrcDkwNRZzi
        RIy2ZV01lMcSuFmTkeuzUdvmdyXMZYHHuG4iquguoa25XOz/O8gh8UTnvPyXIsnX9P/PUU
        6J3LF5DXuJuxTsEpLq9fYBYUKlAHhbdl8gtWDG65drjc/dHtEdVjlZVtg5RS1XbC5NZ80m
        tmXypeN8AKJjy9WS3QNkrh9Hle7MRUEHnpAidUhYD+/kfVgaL0+jluyAlqTeoKm2buJ222
        r6xicZVlOgF4DQ8aHDoZxgxuK20ge94nGuS3cXP/Z29utPQMdbbZp59CvvWPXa0Lu0ki7l
        p1p0q/V292KpXMrkwZ6kqptcFtZZYujGvjRZJ4oVlEIHmAwVCNvoX39Q2MnZjCTmlynUNQ
        Z1iyELWDOvRsO2TkihyHYDE6F4tNqte1Q2UMrZGieLo1SRihm1G9RV6A3zwCJMaEj/SDFs
        rqAMq6Nl1Ai5XGJoB+/qJOAfYNiZZiq6yaql4khbG7Nvie9FpAZtoaZmG/p1sT10bT+0if
        2kSZ23oV/SAlJ5LvVsfRf58Z3ARn2rNXDroK8uqH/fD0RwnX9TYlftIy40IMBcopzS2Q6N
        lTk5vlc9S3TLnGTljEvG5u/etlHIy4po6wYhRnqKj3CoGeJJ8EIlCk+asIAOm00otX5Sgg
        PuiyfKmrPMFjf6Zcp0NQQ8fYZQ3VmFVOJ2PN93kfc9cm9oVOBA4JhFFq6EOe47yfqSoblz
        Jt1gRLHTmMXGoLqw1FNtk19LZbMR8E8cNDouevE3VGMPBZ0cXsoQWVFqynG5KwBXo/1gj3
        4DmIsqDsTJCz652TnvibSWZBzoUU3AjAErzRBQXZPtjES0/g1gRMhdnBWPo/Mh9NJ2dT4O
        oZNRAsjpFco/O/38PwQCzulii+5X8=
        -----END OPENSSH PRIVATE KEY-----
        """
    /// The base64 body (after "ssh-rsa ") of the encrypted RSA key's .pub file.
    private let encryptedRSAPubB64 =
        "AAAAB3NzaC1yc2EAAAADAQABAAABAQDWZwib2Xs24kqvkfd17EwR/oZM5Wyk62trNPC2JSI7YuZOMQVVkB75fTnxby17d4wA+Imtz9LC4jEzwZu5+lfhbW5ifTYYbTlTNwzrKe4/gLygVpFn0uT0SprnSSpJEx3m+4+YnycLsPn4T5xLEja27S7T6eVo+KDqgYGzdShotYUF6UNhJZ7H6tWBPp2Ei+9gHmgII7f8ZpdSxjXI3GfiatMDdp395bckT6Y3AgS9KWZbB5gWBnPs/rMuewAJe7b3AdsTtJIhsU+81Ozv9CkZ2F+nfsesCMU62IC6ctfK5Jl7Xf4M3/lLLvJ2IEPX05iTQh2TjQf59y+td5HnPdP3"

    /// Recomputes the `ssh-rsa` public-key blob (`string "ssh-rsa"`, `mpint e`,
    /// `mpint n`) from the parsed components, so it can be checked against the .pub
    /// blob ssh-keygen wrote — the crux of a correct RSA parse. (Pure local encoding;
    /// the full NIOSSHRSA crypto round trip lives in the package's NIOSSHRSATests.)
    private func sshRSAPublicBlobB64(n: [UInt8], e: [UInt8]) -> String {
        func mpint(_ magnitude: [UInt8]) -> [UInt8] {
            var m = Array(magnitude.drop { $0 == 0 })
            if let first = m.first, first & 0x80 != 0 { m.insert(0, at: 0) }
            let len = UInt32(m.count)
            return [
                UInt8(len >> 24 & 0xff), UInt8(len >> 16 & 0xff),
                UInt8(len >> 8 & 0xff), UInt8(len & 0xff),
            ] + m
        }
        var blob = sshStr("ssh-rsa")
        blob += mpint(e)
        blob += mpint(n)
        return Data(blob).base64EncodedString()
    }

    @Test func parsesUnencryptedRSA() throws {
        let parsed = try OpenSSHPrivateKey.parse(pem: unencryptedRSA)
        #expect(parsed.keyType == "ssh-rsa")
        guard case .rsa(_, let e, _, _, _) = parsed.material else {
            Issue.record("expected rsa material")
            return
        }
        #expect(e == [0x01, 0x00, 0x01]) // standard RSA public exponent 65537
    }

    /// The whole point: the parsed RSA components must reconstruct the exact
    /// `ssh-rsa` public-key blob ssh-keygen wrote to the .pub file.
    @Test func parsedRSAComponentsRebuildTheStoredPublicKey() throws {
        let parsed = try OpenSSHPrivateKey.parse(pem: unencryptedRSA)
        guard case .rsa(let n, let e, _, _, _) = parsed.material else {
            Issue.record("expected rsa material")
            return
        }
        #expect(sshRSAPublicBlobB64(n: n, e: e) == unencryptedRSAPubB64)
    }

    /// bcrypt_pbkdf + AES-CTR over an RSA key: decrypting with the right passphrase
    /// must rebuild the encrypted key's real public blob.
    @Test func decryptsPassphraseProtectedRSA() throws {
        let parsed = try OpenSSHPrivateKey.parse(pem: encryptedRSA, passphrase: "hunter2")
        #expect(parsed.keyType == "ssh-rsa")
        guard case .rsa(let n, let e, _, _, _) = parsed.material else {
            Issue.record("expected rsa material")
            return
        }
        #expect(sshRSAPublicBlobB64(n: n, e: e) == encryptedRSAPubB64)
    }

    // MARK: - Cleartext public-key info (no passphrase needed)

    /// ssh-keygen fingerprints of the embedded test keys (`ssh-keygen -lf …`).
    private let unencryptedRSAFingerprint = "SHA256:RI4GbBb1zha+dgzo5E6wTgHVT5xoW4qF1KLNB8heuwA"
    private let encryptedRSAFingerprint = "SHA256:lWJl7ExjRWqIV8878XGjfEcjreg94f6zv8UBRW9r/H4"

    @Test func publicKeyInfoMatchesSSHKeygenForRSA() throws {
        let info = try #require(OpenSSHPrivateKey.publicKeyInfo(pem: unencryptedRSA))
        #expect(info.keyType == "ssh-rsa")
        #expect(SSHKeyService.fingerprint(blob: info.blob) == unencryptedRSAFingerprint)
    }

    /// The crux of the fix: the public blob (and thus type + fingerprint) is readable
    /// from an *encrypted* key **without** the passphrase.
    @Test func publicKeyInfoReadsEncryptedRSAWithoutPassphrase() throws {
        let info = try #require(OpenSSHPrivateKey.publicKeyInfo(pem: encryptedRSA))
        #expect(info.keyType == "ssh-rsa")
        #expect(SSHKeyService.fingerprint(blob: info.blob) == encryptedRSAFingerprint)
    }

    @Test func publicKeyInfoHandlesEd25519() throws {
        let info = try #require(OpenSSHPrivateKey.publicKeyInfo(pem: unencryptedEd25519))
        #expect(info.keyType == "ssh-ed25519")
        #expect(SSHKeyService.fingerprint(blob: info.blob)?.hasPrefix("SHA256:") == true)
    }

    @Test func publicKeyInfoRejectsNonOpenSSH() {
        #expect(OpenSSHPrivateKey.publicKeyInfo(pem: "not a key") == nil)
    }

    @Test func isEncryptedDetectsCipher() {
        #expect(OpenSSHPrivateKey.isEncrypted(pem: encryptedRSA) == true)
        #expect(OpenSSHPrivateKey.isEncrypted(pem: encryptedEd25519) == true)
        #expect(OpenSSHPrivateKey.isEncrypted(pem: unencryptedRSA) == false)
        #expect(OpenSSHPrivateKey.isEncrypted(pem: unencryptedEd25519) == false)
        // Unparseable input is `nil` (unknown), NOT a definitive `false` — so it isn't
        // audited as "has no passphrase" (audit #33).
        #expect(OpenSSHPrivateKey.isEncrypted(pem: "not a key") == nil)
        #expect(
            OpenSSHPrivateKey.isEncrypted(
                pem:
                    "-----BEGIN OPENSSH PRIVATE KEY-----\n@@@not base64@@@\n-----END OPENSSH PRIVATE KEY-----") == nil)
    }

    @Test func classicPEMAlgorithmDetectsType() {
        #expect(SSHKeyService.classicPEMAlgorithm("-----BEGIN RSA PRIVATE KEY-----\n…") == "ssh-rsa")
        #expect(SSHKeyService.classicPEMAlgorithm("-----BEGIN EC PRIVATE KEY-----\n…") == "ecdsa")
        #expect(SSHKeyService.classicPEMAlgorithm("-----BEGIN DSA PRIVATE KEY-----\n…") == "ssh-dss")
        #expect(SSHKeyService.classicPEMAlgorithm("-----BEGIN PRIVATE KEY-----\n…") == "") // PKCS#8
    }

    // MARK: - Key discovery (the bug: standalone private keys must be listed)

    private let classicRSAPEM = """
        -----BEGIN RSA PRIVATE KEY-----
        MIIBOgIBAAJBAKj34GkxFhD90vcNLYLInFEX6Ppy1tPf9Cnzj4p4WGeKLs1Pt8Qu
        KUpRKfFLfRYC9AIKjbJTWit+CqvjWYzvQwECAwEAAQ==
        -----END RSA PRIVATE KEY-----
        """

    @Test func discoverKeysListsStandalonePrivateKeysAndPairsPublics() throws {
        let dir = URL(fileURLWithPath: "/Users/test/.ssh")
        func u(_ name: String) -> URL { dir.appendingPathComponent(name) }
        let files = [
            u("id_rsa"), u("id_rsa.pub"), // paired public + private
            u("legacy-enc"),
            u("prod.pem"), // standalone classic-PEM private, no .pub
            u("config"), u("known_hosts"), // must be ignored
        ]
        let contents: [String: String] = [
            "id_rsa": unencryptedRSA,
            "id_rsa.pub": "ssh-rsa \(unencryptedRSAPubB64) rsa-test@local",
            "legacy-enc": encryptedRSA,
            "prod.pem": classicRSAPEM,
            "config": "Host foo\n  HostName example.com\n",
            "known_hosts": "example.com ssh-ed25519 AAAAC3...\n",
        ]
        let keys = SSHKeyService.discoverKeys(files: files) { contents[$0.lastPathComponent] }
        let names = keys.map(\.name)

        // The bug fix: standalone private keys (no .pub) are now listed…
        #expect(names.contains("legacy-enc"))
        #expect(names.contains("prod.pem"))
        // …while non-key files are not.
        #expect(!names.contains("config"))
        #expect(!names.contains("known_hosts"))

        let paired = try #require(keys.first { $0.name == "id_rsa" })
        #expect(paired.publicKeyURL != nil)
        #expect(paired.privateKeyURL != nil)
        #expect(paired.fingerprint == unencryptedRSAFingerprint)

        // Standalone encrypted key: typed + fingerprinted without a passphrase.
        let standalone = try #require(keys.first { $0.name == "legacy-enc" })
        #expect(standalone.publicKeyURL == nil)
        #expect(standalone.privateKeyURL == u("legacy-enc"))
        #expect(standalone.algorithm == "ssh-rsa")
        #expect(standalone.fingerprint == encryptedRSAFingerprint)
        #expect(standalone.identityFilePath == "/Users/test/.ssh/legacy-enc")

        // Classic PEM: best-effort type, no fingerprint.
        let pem = try #require(keys.first { $0.name == "prod.pem" })
        #expect(pem.algorithm == "ssh-rsa")
        #expect(pem.typeLabel == "RSA")
        #expect(pem.fingerprint.isEmpty)
    }

    @Test func discoverKeysDoesNotDoubleListPairedPrivateKeys() {
        let dir = URL(fileURLWithPath: "/Users/test/.ssh")
        let files = [dir.appendingPathComponent("id_rsa"), dir.appendingPathComponent("id_rsa.pub")]
        let contents = [
            "id_rsa": unencryptedRSA,
            "id_rsa.pub": "ssh-rsa \(unencryptedRSAPubB64) rsa-test@local",
        ]
        let keys = SSHKeyService.discoverKeys(files: files) { contents[$0.lastPathComponent] }
        #expect(keys.count == 1) // one entry, not the .pub + a phantom private
        #expect(keys[0].privateKeyURL != nil)
    }
}
